### ISSUE TITLE
example model

### ISSUE THREAD

**Issue by azulika** [lucidrains/naturalspeech2-pytorch#13]
Thanks for your work.
Are there any pre-trained models (.pt) for this project? If not, do you plan to provide them?
It would be great if there were models available to check how this project works.

**Comment by Curlypla** [comment]
As mentioned in the previous issues, the project is in WIP and therefore trained is not even really possible yet.
Once the project reaches a trainable stage, a lot of experimentation will have to be done and these trainings will take some time

**Comment by a897456** [comment]
> Thanks for your work. Are there any pre-trained models (.pt) for this project? If not, do you plan to provide them? It would be great if there were models available to check how this project works.

![image](https://github.com/lucidrains/naturalspeech2-pytorch/assets/28752526/6af87042-8091-4b77-bdd2-b0e3e67779c5)
I completed the training of 100k steps and got the `.pt` file which includes 5 items, but I don't know how to use it
